### ISSUE TITLE
RFP Kickoff

### ISSUE THREAD

**Issue by juliajankowski** [juliajankowski/Apple-#32]
**Task List:**

- [ ] 1. Finalize RFP Documents
- [ ] 2. Present to Global Team on the final RFP plan and package
- [ ] 3. PEP process
- [ ] 4. Obtain client concurrence on the RFP package
