### ISSUE TITLE
Evaluation and selection

### ISSUE THREAD

**Issue by juliajankowski** [juliajankowski/Apple-#34]
- [ ] Cross function team evaluation of supplier responses
- [ ] Collectively come up with the shortlist of suppliers
- [ ] Best and final offer process - price table only to the final list of suppliers
- [ ] Collect BAFO responses from supplier and perform evaluations
- [ ] Finalize final suppliers and obtain client concurrence
